name: output

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo "version=1.0.0" >> "$GITHUB_OUTPUT"

      - name: Use the version
        run: echo ${{ steps.get_version.outputs.version }} # {{ steps.<step_id>.outputs.<output_name> }}

      - uses: actions/checkout@v3
        id: deploy
          echo "url=preview_url" >> $GITHUB_OUTPUT

      - run: echo ${{ steps.deploy.outputs.url }}
