name: output

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy-preview.outputs.url }}
    steps:
      - uses: actions/checkout@v3
          echo "url=preview_url" >> $GITHUB_OUTPUT

  data:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: load json files
        run: echo ${{ needs.deploy.outputs.url }}
